#!/usr/bin/env bash
### Description: This script is used to install the core VPTP software.
### Author: deadb33r
### Version: 1.0
### Date: 2024 12 28
### License: MIT

echo "
██    ██ ██████  ████████ ██████  ███████ ██ 
██    ██ ██   ██    ██    ██   ██ ██      ██ 
██    ██ ██████     ██    ██████  ███████ ██ 
 ██  ██  ██         ██    ██           ██ ██ 
  ████   ██         ██    ██      ███████ ██ 
                                             
        VPTP Software Installer (VPTPSI)                                   
                                               "

echo "Installing dependencies..."
sudo apt update
# apt managed packages
sudo apt install -y can-utils \ 
                    pipx \
                    
# pip managed packages
sudo              